# Generated by Django 5.1.7 on 2025-04-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_address_address_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
