# Generated by Django 5.1.7 on 2025-04-11 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
