# Generated by Django 5.1.7 on 2025-03-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], default='Neutral', max_length=10),
        ),
    ]
