# Generated by Django 5.1.7 on 2025-03-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='engagement_level',
            field=models.IntegerField(choices=[(0, 'Visit'), (1, 'Search'), (2, 'Add to Cart'), (3, 'Payment Page')], default=0),
            preserve_default=False,
        ),
    ]
