# Generated by Django 5.1.7 on 2025-03-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_remove_lead_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='sentiment',
        ),
    ]
