# Generated by Django 5.1.7 on 2025-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_remove_lead_sentiment'),
        ('store', '0026_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
